import {
  LayoutDashboard,
  Calendar,
  ClipboardList,
  Wrench,
  UserPlus,
  FileText,
  CheckCircle,
  Truck,
  CreditCard,
  Camera,
  PenTool,
  Package,
  Play,
  MapPin,
  Settings,
  Users,
  BarChart3,
  BookOpen,
  Bell,
  Search,
  Phone,
  Clock,
  Eye,
  List,
  type LucideIcon,
} from 'lucide-react';
import type { AppRole } from '@/types/database';

export interface OnboardingStepContent {
  id: string;
  title: string;
  description: string;
  details: string[];
  fallbackIcon: LucideIcon;
  page?: string;
  tourSelector?: string;
}

// ONBOARDING DONO - 22 Passos
const DONO_STEPS: OnboardingStepContent[] = [
  {
    id: 'dono-welcome',
    title: 'Bem-vindo ao TECNOFRIO',
    description: 'Este é o seu centro de controlo. Aqui gere toda a operação — serviços, técnicos, finanças e equipas. Vamos mostrar-lhe tudo o que precisa saber.',
    details: [],
    fallbackIcon: BookOpen,
  },
  {
    id: 'dono-sidebar',
    title: 'Sidebar — Navegação Principal',
    description: 'A barra lateral é a sua bússola. Cada secção tem uma função específica.',
    details: [
      'Dashboard: visão geral com contadores de estado',
      'Geral: gestão completa de todos os serviços',
      'Oficina: serviços fisicamente na oficina',
      'Clientes: base de dados de clientes',
      'Orçamentos: propostas e conversões',
      'Performance: carga de trabalho por técnico',
      'Colaboradores: gerir equipa e acessos',
      'Preferências: tema, notificações, senha e guia',
    ],
    fallbackIcon: List,
    page: '/dashboard',
    tourSelector: '[data-tour="sidebar-menu"]',
  },
  {
    id: 'dono-dashboard-cards',
    title: 'Dashboard — Contadores de Estado',
    description: 'O Dashboard mostra o estado de toda a operação num relance. Cada card é um contador que se actualiza em tempo real.',
    details: [
      'Cards com contagem > 0 ficam destacados (mais claros)',
      'Cards vazios ficam discretos (mais escuros)',
      'Clicar num card leva directamente para a lista filtrada',
      'Histórico de actividades recentes aparece abaixo',
    ],
    fallbackIcon: LayoutDashboard,
    page: '/dashboard',
    tourSelector: '[data-tour="dashboard-cards"]',
  },
  {
    id: 'dono-dashboard-history',
    title: 'Dashboard — Histórico de Actividades',
    description: 'Abaixo dos contadores, o histórico mostra tudo o que aconteceu recentemente: serviços criados, técnicos atribuídos, peças pedidas e pagamentos registados.',
    details: [],
    fallbackIcon: Clock,
    page: '/dashboard',
    tourSelector: '[data-tour="activity-history"]',
  },
  {
    id: 'dono-geral',
    title: 'Página Geral — Visão Completa',
    description: 'A página Geral é onde tudo acontece. Aqui vê, pesquisa, filtra e gere todos os serviços do sistema.',
    details: [
      'Botão "Novo Serviço" no canto superior direito',
      'Barra de pesquisa por código, cliente ou equipamento',
      'Agenda semanal dinâmica (quando sem filtro activo)',
      'Tabela com Tipo, Código, Cliente, Descrição, Estado, Tags, Técnico, Data + Turno e Acções',
    ],
    fallbackIcon: ClipboardList,
    page: '/geral',
    tourSelector: '[data-tour="geral-header"]',
  },
  {
    id: 'dono-agenda',
    title: 'Agenda Semanal/Mensal',
    description: 'A agenda mostra quantos serviços existem por dia e por técnico, com códigos de cores.',
    details: [
      'Pode alternar entre vista Semanal e Mensal',
      'Cada dia mostra bolhas coloridas por técnico',
      'Clicar num dia abre o drawer lateral com a lista detalhada',
      'Navegar entre semanas/meses com as setas',
    ],
    fallbackIcon: Calendar,
    page: '/geral',
    tourSelector: '[data-tour="weekly-agenda"]',
  },
  {
    id: 'dono-novo-servico',
    title: 'Criar Serviço — Dropdown',
    description: 'Clique em "Novo Serviço" para escolher o tipo. O tipo escolhido define todo o fluxo do serviço.',
    details: [
      'Nova Reparação: o técnico diagnostica e repara',
      'Nova Instalação: montagem de equipamento novo',
      'Nova Entrega Directa: levar equipamento ao cliente',
    ],
    fallbackIcon: FileText,
    page: '/geral',
    tourSelector: '[data-tour="new-service-btn"]',
  },
  {
    id: 'dono-criar-reparacao',
    title: 'Criar Reparação — Modal',
    description: 'Ao criar uma reparação, preencha os dados do cliente e do equipamento. Escolha se o técnico vai ao cliente (Visita) ou se o aparelho já está na oficina.',
    details: [
      'Campo Cliente com autocomplete',
      'Botão para criar cliente novo inline',
      'Checkbox "Urgente" marca serviço como prioritário',
      'Checkbox "Garantia" marca serviço sem cobrança',
      'A escolha Visita vs Oficina define o fluxo do técnico',
    ],
    fallbackIcon: Wrench,
  },
  {
    id: 'dono-tabela',
    title: 'Tabela de Serviços — Colunas e Badges',
    description: 'Cada linha da tabela mostra toda a informação essencial do serviço.',
    details: [
      'Badge de Tipo: azul para visita, roxo para oficina, amarelo para instalação, verde para entrega',
      'Badge de Estado: cor distinta para cada fase do fluxo',
      'Tags coexistentes: um serviço pode ser Urgente + Garantia + A Precificar ao mesmo tempo',
      'O técnico aparece com avatar colorido',
      'Data e turno (Manhã/Tarde) com ícone',
    ],
    fallbackIcon: ClipboardList,
    page: '/geral',
    tourSelector: '[data-tour="services-table"]',
  },
  {
    id: 'dono-accoes',
    title: 'Botões de Acção por Estado',
    description: 'Os botões de acção mudam conforme o estado do serviço. O sistema mostra apenas as acções possíveis naquele momento.',
    details: [
      '"Atribuir" quando sem técnico',
      '"Precificar" quando pending_pricing',
      '"Registar Pagamento" quando em débito',
      '"Gerir Entrega" quando concluído na oficina',
      '"Forçar Estado" para excepções administrativas',
    ],
    fallbackIcon: Play,
    page: '/geral',
    tourSelector: '[data-tour="action-buttons"]',
  },
  {
    id: 'dono-ficha',
    title: 'Ficha Lateral (ServiceDetailSheet)',
    description: 'Clique em qualquer serviço para abrir a ficha completa. Aqui vê tudo: dados, histórico, fotos, assinaturas e pagamentos.',
    details: [
      'Cabeçalho com código grande, badge de estado e tipo',
      'Secção do cliente com nome, telefone, email e morada',
      'Secção do equipamento com tipo, marca, modelo e avaria',
      'Secção do técnico com avatar e nome',
      'Botões de acção na ficha (Atribuir, Precificar, Contactar, etc.)',
    ],
    fallbackIcon: Eye,
  },
  {
    id: 'dono-timeline',
    title: 'Ficha Lateral — Timeline e Histórico',
    description: 'A ficha regista toda a história do serviço automaticamente.',
    details: [
      'Timeline com cada mudança de estado datada',
      'Galeria de fotos do diagnóstico (aparelho, etiqueta, estado)',
      'Assinaturas digitais do cliente (recolha, entrega, pedido de peça)',
      'Histórico de pagamentos com valores e datas',
      'Peças usadas e peças encomendadas',
    ],
    fallbackIcon: Clock,
  },
  {
    id: 'dono-atribuir',
    title: 'Atribuir Técnico — Modal',
    description: 'Atribua um técnico e agende a data. O técnico recebe o serviço automaticamente na sua agenda.',
    details: [
      'Lista de técnicos activos com avatar colorido',
      'Campo de data com calendário',
      'Selecção de turno: Manhã ou Tarde',
      'Ao confirmar, o técnico é notificado',
    ],
    fallbackIcon: UserPlus,
  },
  {
    id: 'dono-precificar',
    title: 'Precificar Serviço — Modal',
    description: 'Defina o preço do serviço adicionando linhas de orçamento. Pode incluir mão-de-obra, peças e deslocação.',
    details: [
      'Adicionar múltiplas linhas de preço',
      'Cada linha: descrição, referência, quantidade, preço unitário',
      'Cálculo automático do total',
      'Resumo com subtotal e total final',
      'Serviços em garantia não exigem precificação',
    ],
    fallbackIcon: CreditCard,
  },
  {
    id: 'dono-pedido-peca',
    title: 'Pedido de Peça — Fluxo Completo',
    description: 'Quando o técnico pede uma peça, você recebe uma notificação. Registe a encomenda com fornecedor e previsão de chegada.',
    details: [
      'O técnico regista a necessidade de peça no terreno',
      'Notificação aparece no sino (canto superior direito)',
      'Modal de confirmação: fornecedor, referência e data prevista',
      'Indicador de termómetro mostra proximidade da chegada',
      'Quando a peça chega, registar via "Peça Chegou"',
    ],
    fallbackIcon: Package,
  },
  {
    id: 'dono-notificacoes',
    title: 'Notificações',
    description: 'O sino no canto superior mostra notificações não lidas. Inclui pedidos de peça, atribuições, precificações e alertas.',
    details: [
      'Badge vermelho com contagem de não lidas',
      'Tipos: peça pedida, peça chegou, serviço atribuído, precificação, entrega agendada',
      'Marcar como lida individualmente ou todas de uma vez',
      'Clique na notificação para ir ao serviço',
    ],
    fallbackIcon: Bell,
    tourSelector: '[data-tour="notifications-btn"]',
  },
  {
    id: 'dono-oficina',
    title: 'Página Oficina — Cards de Serviço',
    description: 'A página Oficina mostra serviços fisicamente presentes na oficina, organizados em cards visuais.',
    details: [
      'Borda esquerda colorida: roxa para normal, vermelha para urgente',
      'Badge de estado dinâmico',
      'Se sem técnico: destaque amarelo com botão "Atribuir"',
      'Se com técnico: avatar e botão "Reatribuir"',
      'Botão "Enviar Tarefa" para dar instruções específicas',
    ],
    fallbackIcon: Wrench,
    page: '/oficina',
    tourSelector: '[data-tour="oficina-cards"]',
  },
  {
    id: 'dono-clientes',
    title: 'Página Clientes',
    description: 'Gerir toda a base de clientes. Pesquise, crie novos e veja o histórico de serviços de cada um.',
    details: [
      'Pesquisa por nome, email ou telefone',
      'Tipo: Final ou Empresa (badge)',
      'Botão "..." com opções: Ver Perfil, Editar, Eliminar',
      'Ficha do cliente abre em Sheet lateral com histórico de serviços',
      'Paginação para grandes volumes',
    ],
    fallbackIcon: Users,
    page: '/clientes',
    tourSelector: '[data-tour="clientes-header"]',
  },
  {
    id: 'dono-orcamentos',
    title: 'Página Orçamentos',
    description: 'Crie e gira propostas de orçamento. Aprove, recuse ou converta em serviço.',
    details: [
      'Estados: Pendente (amarelo), Aprovado (verde), Recusado (vermelho), Convertido (azul)',
      'Acções contextuais: Aprovar, Recusar, Converter em Serviço, Editar, Excluir',
      'Converter: transforma orçamento aprovado em serviço real',
      'Ficha detalhada em painel lateral com impressão PDF',
    ],
    fallbackIcon: FileText,
    page: '/orcamentos',
    tourSelector: '[data-tour="orcamentos-header"]',
  },
  {
    id: 'dono-performance',
    title: 'Página Performance',
    description: 'Visualize a carga de trabalho de cada técnico com gráficos e métricas.',
    details: [
      'Card por técnico com avatar e cor',
      'Contadores: Entregas, Instalações, Reparações',
      'Gráfico de pizza com proporção por tipo',
      'Lista dos últimos 10 serviços com estado',
    ],
    fallbackIcon: BarChart3,
    page: '/performance',
    tourSelector: '[data-tour="performance-cards"]',
  },
  {
    id: 'dono-colaboradores',
    title: 'Página Colaboradores',
    description: 'Gira a equipa. Convide novos colaboradores, edite dados e controle acessos.',
    details: [
      'Convidar por email com password inicial e cargo',
      'Cargos: Administrador, Secretária, Técnico',
      'Técnicos podem ser desactivados (não recebem serviços)',
      'Excluir permanentemente remove o utilizador',
      'Filtro por cargo e pesquisa por nome/email',
    ],
    fallbackIcon: Users,
    page: '/colaboradores',
    tourSelector: '[data-tour="colaboradores-header"]',
  },
  {
    id: 'dono-final',
    title: 'Começar a Usar',
    description: 'Você controla decisões, excepções e finanças. O sistema cuida do resto — regista, notifica e garante continuidade. Bom trabalho!',
    details: [],
    fallbackIcon: CheckCircle,
  },
];

// ONBOARDING SECRETÁRIA - 16 Passos
const SECRETARIA_STEPS: OnboardingStepContent[] = [
  {
    id: 'sec-welcome',
    title: 'Bem-vinda ao TECNOFRIO',
    description: 'O seu papel é essencial: organizar serviços, gerir entregas e manter o caixa em dia.',
    details: [],
    fallbackIcon: BookOpen,
  },
  {
    id: 'sec-sidebar',
    title: 'Sidebar — Navegação',
    description: 'A sua barra lateral tem acesso directo às secções mais importantes para o dia-a-dia.',
    details: [
      'Geral: criar e acompanhar serviços',
      'Oficina: ver serviços na oficina',
      'Oficina Reparados: gerir entregas de serviços concluídos',
      'Em Débito: cobrar pagamentos pendentes',
      'Clientes: base de dados',
      'Preferências: tema, notificações, senha',
    ],
    fallbackIcon: List,
    page: '/geral',
    tourSelector: '[data-tour="sidebar-menu"]',
  },
  {
    id: 'sec-geral',
    title: 'Página Geral — Criar e Gerir',
    description: 'Quando um cliente liga, crie o serviço aqui. Preencha os dados, escolha o tipo e atribua a um técnico.',
    details: [],
    fallbackIcon: ClipboardList,
    page: '/geral',
    tourSelector: '[data-tour="new-service-btn"]',
  },
  {
    id: 'sec-pesquisa',
    title: 'Pesquisa e Filtros',
    description: 'Pesquise por código, nome do cliente ou equipamento. A tabela filtra instantaneamente.',
    details: [],
    fallbackIcon: Search,
    page: '/geral',
    tourSelector: '[data-tour="search-bar"]',
  },
  {
    id: 'sec-atribuir',
    title: 'Atribuir Técnico e Agendar',
    description: 'Seleccione o técnico, a data e o turno. O técnico vê o serviço automaticamente na sua agenda.',
    details: [],
    fallbackIcon: UserPlus,
  },
  {
    id: 'sec-oficina',
    title: 'Página Oficina — Acompanhamento',
    description: 'Acompanhe os serviços na oficina. Veja o estado, o técnico atribuído e se há urgências.',
    details: [],
    fallbackIcon: Wrench,
    page: '/oficina',
    tourSelector: '[data-tour="oficina-cards"]',
  },
  {
    id: 'sec-concluidos',
    title: 'Oficina Reparados — Gerir Entregas',
    description: 'Serviços reparados aparecem aqui. Defina o método de entrega e contacte o cliente.',
    details: [
      '"Gerir Entrega": escolher entre técnico entrega ou cliente recolhe',
      '"Dar Baixa": quando o cliente recolhe pessoalmente',
      'Indicador de dias na oficina (vermelho se > 30 dias)',
      'Botão telefone para contactar o cliente',
    ],
    fallbackIcon: Truck,
    page: '/concluidos',
    tourSelector: '[data-tour="concluidos-header"]',
  },
  {
    id: 'sec-gerir-entrega',
    title: 'Gerir Entrega — Modal',
    description: 'Escolha como o aparelho chega ao cliente. Se por técnico, atribua a entrega a um técnico específico.',
    details: [],
    fallbackIcon: Truck,
  },
  {
    id: 'sec-debito',
    title: 'Em Débito — Pagamentos Pendentes',
    description: 'Todos os serviços com pagamento pendente estão aqui. Veja exactamente quanto falta cobrar.',
    details: [
      'Valor total em preto',
      'Já pago em verde',
      'Em falta em vermelho e negrito',
      'Badge com total em débito no cabeçalho',
    ],
    fallbackIcon: CreditCard,
    page: '/em-debito',
    tourSelector: '[data-tour="debito-header"]',
  },
  {
    id: 'sec-pagamento',
    title: 'Registar Pagamento — Modal',
    description: 'Registe pagamentos parciais ou totais. O sistema calcula automaticamente o valor restante.',
    details: [
      'Campo de valor pré-preenchido com o montante em falta',
      'Pagamento parcial: o serviço continua em débito',
      'Pagamento total: o débito é liquidado',
    ],
    fallbackIcon: CreditCard,
  },
  {
    id: 'sec-contactar',
    title: 'Contactar Cliente — Modal',
    description: 'Contacte o cliente directamente. O modal mostra todos os dados de contacto disponíveis.',
    details: [],
    fallbackIcon: Phone,
  },
  {
    id: 'sec-ficha',
    title: 'Ficha Lateral do Serviço',
    description: 'Clique em qualquer serviço para ver os detalhes completos. A ficha lateral mostra tudo sem mudar de página.',
    details: [],
    fallbackIcon: Eye,
  },
  {
    id: 'sec-clientes',
    title: 'Clientes — Gestão',
    description: 'Consulte e edite os dados dos clientes. Crie novos clientes e veja o histórico de serviços associados.',
    details: [],
    fallbackIcon: Users,
    page: '/clientes',
    tourSelector: '[data-tour="clientes-header"]',
  },
  {
    id: 'sec-notificacoes',
    title: 'Notificações',
    description: 'O sino no topo alerta-a para eventos importantes: peças pedidas, serviços atribuídos e alertas urgentes.',
    details: [],
    fallbackIcon: Bell,
    tourSelector: '[data-tour="notifications-btn"]',
  },
  {
    id: 'sec-preferencias',
    title: 'Preferências',
    description: 'Configure o tema (claro/escuro), as notificações, altere a password e reveja este guia a qualquer momento.',
    details: [],
    fallbackIcon: Settings,
    page: '/preferencias',
    tourSelector: '[data-tour="preferencias-header"]',
  },
  {
    id: 'sec-final',
    title: 'Começar a Usar',
    description: 'Mantém o fluxo a andar e o caixa organizado. O sistema ajuda-a em cada passo.',
    details: [],
    fallbackIcon: CheckCircle,
  },
];

// ONBOARDING TÉCNICO - 18 Passos
const TECNICO_STEPS: OnboardingStepContent[] = [
  {
    id: 'tec-welcome',
    title: 'Bem-vindo ao TECNOFRIO',
    description: 'Este é o seu espaço de trabalho. Aqui vê o que tem de fazer e regista tudo o que faz.',
    details: [],
    fallbackIcon: BookOpen,
  },
  {
    id: 'tec-sidebar',
    title: 'Sidebar — Navegação',
    description: 'A sua barra lateral é simples e directa.',
    details: [
      'Serviços: agenda diária com serviços atribuídos',
      'Oficina: serviços na oficina para reparar',
      'Perfil: os seus dados e estatísticas',
      'Preferências: tema, notificações e senha',
    ],
    fallbackIcon: List,
    page: '/servicos',
    tourSelector: '[data-tour="sidebar-menu"]',
  },
  {
    id: 'tec-agenda',
    title: 'Página Serviços — Agenda Diária',
    description: 'Os seus serviços aparecem organizados por dia. Navegue entre dias com as setas.',
    details: [
      'Botão central mostra a data actual (destacado quando é hoje)',
      'Secções por turno: Manhã (sol nascente) e Tarde (sol)',
      'Cada secção mostra o total de serviços',
      'Se não há serviços, mensagem "Sem serviços para este dia"',
    ],
    fallbackIcon: Calendar,
    page: '/servicos',
    tourSelector: '[data-tour="servicos-agenda"]',
  },
  {
    id: 'tec-cards',
    title: 'Cards de Serviço — Tipos Visuais',
    description: 'Cada card mostra o tipo, o cliente e o equipamento. As cores ajudam a distinguir rapidamente.',
    details: [
      'Borda esquerda colorida: azul (Visita), amarelo (Instalação), verde (Entrega)',
      'Badge de tipo no canto superior direito',
      'Tags: Urgente (vermelho pulsante), Garantia (verde)',
      'Ícone de turno com label',
      'Botão "Começar" em cor do tipo',
    ],
    fallbackIcon: ClipboardList,
    page: '/servicos',
    tourSelector: '[data-tour="service-cards"]',
  },
  {
    id: 'tec-comecar',
    title: 'Começar Serviço — Botão',
    description: 'Quando estiver pronto, clique em "Começar". O sistema guia-o passo a passo até ao fim.',
    details: [],
    fallbackIcon: Play,
    page: '/servicos',
    tourSelector: '[data-tour="start-service-btn"]',
  },
  {
    id: 'tec-resumo',
    title: 'Fluxo de Visita — Resumo Anterior',
    description: 'Se outro técnico já atendeu este serviço, verá o resumo completo antes de começar. Isto garante continuidade.',
    details: [],
    fallbackIcon: Eye,
  },
  {
    id: 'tec-gps',
    title: 'Fluxo de Visita — Deslocação (GPS)',
    description: 'O primeiro passo mostra o endereço do cliente. Clique para abrir a navegação GPS.',
    details: [],
    fallbackIcon: MapPin,
  },
  {
    id: 'tec-fotos',
    title: 'Fluxo de Visita — Fotos Obrigatórias',
    description: 'Tire fotos obrigatórias do aparelho: foto geral, etiqueta (modelo/série) e estado actual.',
    details: [
      'Câmera abre directamente no modal',
      '3 tipos de foto: aparelho, etiqueta, estado',
      'Cada foto pode ser retirada se ficar mal',
      'As fotos ficam associadas ao serviço permanentemente',
    ],
    fallbackIcon: Camera,
  },
  {
    id: 'tec-diagnostico',
    title: 'Fluxo de Visita — Diagnóstico',
    description: 'Descreva a avaria detectada. Este campo é obrigatório e fica visível para o escritório.',
    details: [],
    fallbackIcon: Wrench,
  },
  {
    id: 'tec-decisao',
    title: 'Fluxo de Visita — Decisão Principal',
    description: 'Esta é a decisão mais importante. Cada escolha adapta o fluxo seguinte.',
    details: [
      'Reparar no Local: pede peças usadas, conclui e pede assinatura',
      'Levar para Oficina: pede assinatura de autorização de transporte',
      'Precisa de Peça: regista o pedido e pede assinatura de autorização',
    ],
    fallbackIcon: Play,
  },
  {
    id: 'tec-pecas',
    title: 'Peças Usadas — Modal',
    description: 'Se reparou no local, registe as peças que utilizou. Pode adicionar várias peças com quantidades.',
    details: [],
    fallbackIcon: Package,
  },
  {
    id: 'tec-assinatura',
    title: 'Assinatura Digital',
    description: 'O cliente assina no ecrã para confirmar a decisão. Pode limpar e refazer se errar.',
    details: [
      'Canvas de desenho livre',
      'Botão "Limpar" apaga a assinatura',
      'Botão "Cancelar" volta ao passo anterior',
      'Tipos: autorização de transporte, confirmação de reparação, autorização de pedido de peça',
    ],
    fallbackIcon: PenTool,
  },
  {
    id: 'tec-pedir-peca',
    title: 'Pedir Peça — Fluxo',
    description: 'Se precisa de uma peça, registe o pedido. O escritório é notificado automaticamente e encomenda por si.',
    details: [
      'Descrição da peça necessária',
      'Notas adicionais',
      'Assinatura do cliente para autorizar',
      'O serviço muda para "Para Pedir Peça"',
      'Quando a peça chega, o serviço volta a ficar disponível',
    ],
    fallbackIcon: Package,
  },
  {
    id: 'tec-oficina',
    title: 'Oficina do Técnico — Página',
    description: 'Na oficina, veja serviços sem técnico que pode assumir e os seus próprios serviços.',
    details: [
      'Secção superior: cards cinzentos para serviços disponíveis com botão "Assumir Serviço"',
      'Secção inferior: cards laranjas para serviços próprios com botão "Começar"',
      'Badge de estado em cada card',
      'Botão de transferência para solicitar que outro técnico assuma',
    ],
    fallbackIcon: Wrench,
    page: '/oficina-tecnico',
    tourSelector: '[data-tour="oficina-tecnico"]',
  },
  {
    id: 'tec-fluxo-oficina',
    title: 'Fluxo de Oficina',
    description: 'O fluxo de oficina é semelhante mas sem deslocação. Diagnostique, registe o trabalho e conclua.',
    details: [],
    fallbackIcon: Settings,
  },
  {
    id: 'tec-perfil',
    title: 'Perfil — Estatísticas Pessoais',
    description: 'O seu perfil mostra as suas estatísticas: total de serviços, serviços este mês e serviços activos.',
    details: [
      'Editar nome e telefone',
      'Ver especialização',
      'Contador de serviços total, este mês e activos',
      'Data de registo e estado da conta',
    ],
    fallbackIcon: Users,
    page: '/perfil',
    tourSelector: '[data-tour="perfil-header"]',
  },
  {
    id: 'tec-preferencias',
    title: 'Preferências',
    description: 'Configure o tema visual, as notificações e altere a sua password. Pode rever este guia a qualquer momento.',
    details: [],
    fallbackIcon: Settings,
    page: '/preferencias',
    tourSelector: '[data-tour="preferencias-header"]',
  },
  {
    id: 'tec-final',
    title: 'Começar a Usar',
    description: 'Execute bem. O sistema regista tudo e garante continuidade se outro técnico assumir. Bom trabalho!',
    details: [],
    fallbackIcon: CheckCircle,
  },
];

export const ONBOARDING_CONTENT: Record<AppRole, OnboardingStepContent[]> = {
  dono: DONO_STEPS,
  secretaria: SECRETARIA_STEPS,
  tecnico: TECNICO_STEPS,
  monitor: [],
};

export function getOnboardingSteps(role: AppRole | null): OnboardingStepContent[] {
  if (!role) return [];
  return ONBOARDING_CONTENT[role] || [];
}
