// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flialeqlwrtfnonxtsnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaWFsZXFsd3J0Zm5vbnh0c254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNTg0MzMsImV4cCI6MjA4NDkzNDQzM30.Dh7YHVUwsFAQEzUcuy1IxBKlCBp9qMJLVK4c1kAkmw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Ensures the current session has a valid (non-expired) token.
 * If the token expires within 60 seconds, forces a refresh.
 * Throws a clear error if no session or refresh fails.
 */
export async function ensureValidSession() {
  const { data, error } = await supabase.auth.getSession();

  if (error || !data.session) {
    // if the session is gone, force a logout and navigate to login to avoid
    // repeated query errors that trigger the error boundary.
    try {
      await supabase.auth.signOut();
    } catch {}
    if (typeof window !== 'undefined') {
      window.location.href = '/login';
    }
    throw new Error('Sessão expirada. Por favor, faça login novamente.');
  }

  const tokenExp = data.session.expires_at;
  const now = Math.floor(Date.now() / 1000);

  if (tokenExp && tokenExp - now < 60) {
    const { data: refreshed, error: refreshError } = await supabase.auth.refreshSession();
    if (refreshError || !refreshed.session) {
      try {
        await supabase.auth.signOut();
      } catch {}
      if (typeof window !== 'undefined') {
        window.location.href = '/login';
      }
      throw new Error('Sessão expirada. Por favor, faça login novamente.');
    }
    return refreshed.session;
  }

  return data.session;
}

/**
 * Checks if an error is related to RLS/session issues.
 */
export function isSessionOrRlsError(error: unknown): boolean {
  const msg = error instanceof Error ? error.message : String(error);
  return msg.includes('row-level security') ||
    msg.includes('JWT') ||
    msg.includes('login novamente') ||
    msg.includes('not authenticated');
}