// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flialeqlwrtfnonxtsnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaWFsZXFsd3J0Zm5vbnh0c254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNTg0MzMsImV4cCI6MjA4NDkzNDQzM30.Dh7YHVUwsFAQEzUcuy1IxBKlCBp9qMJLVK4c1kAkmw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});